spring:
  application:
    name: spinnaker-demo
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
        prometheus:
          pushgateway:
            enabled: true
            job: spinnaker-demo
            base-url: http://10.195.72.141:9091
version: 1.0

---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true